workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.example.swapifymobile"

    scripts:
      - name: Print Flutter, Ruby, and CocoaPods versions
        script: |
          flutter --version
          ruby -v
          pod --version

      - name: Clean previous build files
        script: |
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          flutter clean

      - name: Ensure Flutter and CocoaPods are correctly installed
        script: |
          flutter precache
          flutter doctor -v

      - name: Install Flutter dependencies
        script: |
          flutter pub get

#      - name: Generate Podfile if missing and set platform to iOS 12.0
#        script: |
#          cd ios
#          if [ ! -f "Podfile" ]; then
#            echo "Creating Podfile..."
#            cat <<EOF > Podfile
#            platform :ios, '12.0'
#            use_frameworks!
#            target 'Runner' do
#              flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
#            end
#            EOF
#          fi
#          cd ..

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update --verbose
          cd ..

      - name: Skip tests (override default behavior)
        script: |
          echo "Skipping tests..."

      - name: Build iOS without code signing
        script: |
          flutter build ios --no-codesign
