workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.example.swapifymobile"

    scripts:
      - name: Print Flutter, Ruby, and CocoaPods versions
        script: |
          flutter --version
          ruby -v
          pod --version

      - name: Clean previous build files
        script: |
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          flutter clean

      - name: Ensure `flutter_install_all_ios_pods` is available
        script: |
          flutter precache
          flutter doctor -v

      - name: Install Flutter dependencies
        script: |
          flutter pub get

      - name: Generate iOS module (if missing)
        script: |
          cd ios
          flutter pub get
          pod deintegrate
          rm -rf Podfile.lock
          pod install --repo-update --verbose
          cd ..

      - name: Build iOS without code signing
        script: |
          flutter build ios --no-codesign
