workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.example.swapifymobile"

    scripts:
      - name: Print Flutter & Ruby versions (for debugging)
        script: |
          flutter --version
          ruby -v
          pod --version

      - name: Clean previous build files
        script: |
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          flutter clean

      - name: Ensure `podhelper.rb` exists
        script: |
          if [ ! -f "ios/flutter/podhelper.rb" ]; then
            echo "ERROR: podhelper.rb is missing! Ensure Flutter module is properly set up."
            exit 1
          fi

      - name: Install Flutter dependencies
        script: |
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update --verbose
          cd ..

      - name: Build iOS without code signing
        script: |
          flutter build ios --no-codesign



#workflows:
#  flutter-app:
#    name: Flutter App Build
#    instance_type: mac_mini_m1 # Use macOS for iOS builds
#
#    environment:
#      flutter: stable
#      xcode: latest
#      cocoapods: default
#
#    scripts:
#      - name: Install dependencies
#        script: |
#          flutter clean
#          flutter pub get
#
#      - name: Build Android APK
#        script: |
#          flutter build apk --release
#
#      - name: Build iOS (No Code Signing)
#        script: |
#          flutter build ios --no-codesign
#          cd ios && pod install && cd ..
#
#    artifacts:
#      - build/app/outputs/flutter-apk/app-release.apk # Android output
#      - build/ios/iphoneos/*.app                      # iOS output
#
#    publishing:
#      email:
#        recipients:
#          - your-email@example.com

