workflows:
#  android-workflow-id:
#    name: Android Sample Workflow
    # .......
    # .......
    # .......
  ios-workflow-id:
    name: iOS Sample Workflow
scripts:
  - name: Build Flutter iOS app
    script: |
      flutter pub get
      flutter clean
      flutter build ios --no-codesign
      cd ios
      pod install
      cd ..
